/**
 * GENERATED FILE — one import per document in this directory.
 * Regenerated by the data pipeline (@fathom/pipeline) on apply; keep in
 * sync by hand only when adding documents manually.
 */
import rawAlbania from './albania.json';
import rawArgentina from './argentina.json';
import rawAustralia from './australia.json';
import rawBahamas from './bahamas.json';
import rawCanada from './canada.json';
import rawChile from './chile.json';
import rawChina from './china.json';
import rawCuba from './cuba.json';
import rawDenmark from './denmark.json';
import rawDjibouti from './djibouti.json';
import rawEgypt from './egypt.json';
import rawEritrea from './eritrea.json';
import rawFrance from './france.json';
import rawGreenland from './greenland.json';
import rawIceland from './iceland.json';
import rawIndia from './india.json';
import rawIndonesia from './indonesia.json';
import rawIran from './iran.json';
import rawItaly from './italy.json';
import rawJapan from './japan.json';
import rawMadagascar from './madagascar.json';
import rawMalaysia from './malaysia.json';
import rawMorocco from './morocco.json';
import rawMozambique from './mozambique.json';
import rawNewZealand from './new-zealand.json';
import rawNorway from './norway.json';
import rawOman from './oman.json';
import rawPanama from './panama.json';
import rawPapuaNewGuinea from './papua-new-guinea.json';
import rawPhilippines from './philippines.json';
import rawRussia from './russia.json';
import rawSingapore from './singapore.json';
import rawSouthKorea from './south-korea.json';
import rawSpain from './spain.json';
import rawSriLanka from './sri-lanka.json';
import rawSweden from './sweden.json';
import rawTaiwan from './taiwan.json';
import rawTurkey from './turkey.json';
import rawUkraine from './ukraine.json';
import rawUnitedKingdom from './united-kingdom.json';
import rawUnitedStates from './united-states.json';
import rawYemen from './yemen.json';

export const RAW_COUNTRY_DOCUMENTS: readonly unknown[] = [
  rawAlbania,
  rawArgentina,
  rawAustralia,
  rawBahamas,
  rawCanada,
  rawChile,
  rawChina,
  rawCuba,
  rawDenmark,
  rawDjibouti,
  rawEgypt,
  rawEritrea,
  rawFrance,
  rawGreenland,
  rawIceland,
  rawIndia,
  rawIndonesia,
  rawIran,
  rawItaly,
  rawJapan,
  rawMadagascar,
  rawMalaysia,
  rawMorocco,
  rawMozambique,
  rawNewZealand,
  rawNorway,
  rawOman,
  rawPanama,
  rawPapuaNewGuinea,
  rawPhilippines,
  rawRussia,
  rawSingapore,
  rawSouthKorea,
  rawSpain,
  rawSriLanka,
  rawSweden,
  rawTaiwan,
  rawTurkey,
  rawUkraine,
  rawUnitedKingdom,
  rawUnitedStates,
  rawYemen,
];
