/**
 * GENERATED FILE — one import per document in this directory.
 * Regenerated by the data pipeline (@fathom/pipeline) on apply; keep in
 * sync by hand only when adding documents manually.
 */
import rawAfghanistan from './afghanistan.json';
import rawAlbania from './albania.json';
import rawAlgeria from './algeria.json';
import rawAndorra from './andorra.json';
import rawAngola from './angola.json';
import rawAntiguaAndBarbuda from './antigua-and-barbuda.json';
import rawArgentina from './argentina.json';
import rawArmenia from './armenia.json';
import rawAustralia from './australia.json';
import rawAustria from './austria.json';
import rawAzerbaijan from './azerbaijan.json';
import rawBahamas from './bahamas.json';
import rawBahrain from './bahrain.json';
import rawBangladesh from './bangladesh.json';
import rawBarbados from './barbados.json';
import rawBelarus from './belarus.json';
import rawBelgium from './belgium.json';
import rawBelize from './belize.json';
import rawBenin from './benin.json';
import rawBhutan from './bhutan.json';
import rawBolivia from './bolivia.json';
import rawBosniaAndHerzegovina from './bosnia-and-herzegovina.json';
import rawBotswana from './botswana.json';
import rawBrazil from './brazil.json';
import rawBrunei from './brunei.json';
import rawBulgaria from './bulgaria.json';
import rawBurkinaFaso from './burkina-faso.json';
import rawBurundi from './burundi.json';
import rawCambodia from './cambodia.json';
import rawCameroon from './cameroon.json';
import rawCanada from './canada.json';
import rawCapeVerde from './cape-verde.json';
import rawCentralAfricanRepublic from './central-african-republic.json';
import rawChad from './chad.json';
import rawChile from './chile.json';
import rawChina from './china.json';
import rawColombia from './colombia.json';
import rawComoros from './comoros.json';
import rawCostaRica from './costa-rica.json';
import rawCroatia from './croatia.json';
import rawCuba from './cuba.json';
import rawCyprus from './cyprus.json';
import rawCzechRepublic from './czech-republic.json';
import rawDemocraticRepublicOfTheCongo from './democratic-republic-of-the-congo.json';
import rawDenmark from './denmark.json';
import rawDjibouti from './djibouti.json';
import rawDominica from './dominica.json';
import rawDominicanRepublic from './dominican-republic.json';
import rawEcuador from './ecuador.json';
import rawEgypt from './egypt.json';
import rawElSalvador from './el-salvador.json';
import rawEquatorialGuinea from './equatorial-guinea.json';
import rawEritrea from './eritrea.json';
import rawEstonia from './estonia.json';
import rawEswatini from './eswatini.json';
import rawEthiopia from './ethiopia.json';
import rawFederatedStatesOfMicronesia from './federated-states-of-micronesia.json';
import rawFiji from './fiji.json';
import rawFinland from './finland.json';
import rawFrance from './france.json';
import rawGabon from './gabon.json';
import rawGeorgia from './georgia.json';
import rawGermany from './germany.json';
import rawGhana from './ghana.json';
import rawGibraltar from './gibraltar.json';
import rawGreece from './greece.json';
import rawGreenland from './greenland.json';
import rawGrenada from './grenada.json';
import rawGuatemala from './guatemala.json';
import rawGuinea from './guinea.json';
import rawGuineaBissau from './guinea-bissau.json';
import rawGuyana from './guyana.json';
import rawHaiti from './haiti.json';
import rawHonduras from './honduras.json';
import rawHungary from './hungary.json';
import rawIceland from './iceland.json';
import rawIndia from './india.json';
import rawIndonesia from './indonesia.json';
import rawIran from './iran.json';
import rawIraq from './iraq.json';
import rawIreland from './ireland.json';
import rawIsrael from './israel.json';
import rawItaly from './italy.json';
import rawIvoryCoast from './ivory-coast.json';
import rawJamaica from './jamaica.json';
import rawJapan from './japan.json';
import rawJordan from './jordan.json';
import rawKazakhstan from './kazakhstan.json';
import rawKenya from './kenya.json';
import rawKingdomOfTheNetherlands from './kingdom-of-the-netherlands.json';
import rawKiribati from './kiribati.json';
import rawKosovo from './kosovo.json';
import rawKuwait from './kuwait.json';
import rawKyrgyzstan from './kyrgyzstan.json';
import rawLaos from './laos.json';
import rawLatvia from './latvia.json';
import rawLebanon from './lebanon.json';
import rawLesotho from './lesotho.json';
import rawLiberia from './liberia.json';
import rawLibya from './libya.json';
import rawLiechtenstein from './liechtenstein.json';
import rawLithuania from './lithuania.json';
import rawLuxembourg from './luxembourg.json';
import rawMadagascar from './madagascar.json';
import rawMalawi from './malawi.json';
import rawMalaysia from './malaysia.json';
import rawMaldives from './maldives.json';
import rawMali from './mali.json';
import rawMalta from './malta.json';
import rawMarshallIslands from './marshall-islands.json';
import rawMauritania from './mauritania.json';
import rawMauritius from './mauritius.json';
import rawMexico from './mexico.json';
import rawMoldova from './moldova.json';
import rawMonaco from './monaco.json';
import rawMongolia from './mongolia.json';
import rawMontenegro from './montenegro.json';
import rawMorocco from './morocco.json';
import rawMozambique from './mozambique.json';
import rawMyanmar from './myanmar.json';
import rawNamibia from './namibia.json';
import rawNauru from './nauru.json';
import rawNepal from './nepal.json';
import rawNewZealand from './new-zealand.json';
import rawNicaragua from './nicaragua.json';
import rawNiger from './niger.json';
import rawNigeria from './nigeria.json';
import rawNorthKorea from './north-korea.json';
import rawNorthMacedonia from './north-macedonia.json';
import rawNorway from './norway.json';
import rawOman from './oman.json';
import rawPakistan from './pakistan.json';
import rawPalau from './palau.json';
import rawPalestine from './palestine.json';
import rawPanama from './panama.json';
import rawPapuaNewGuinea from './papua-new-guinea.json';
import rawParaguay from './paraguay.json';
import rawPeru from './peru.json';
import rawPhilippines from './philippines.json';
import rawPoland from './poland.json';
import rawPortugal from './portugal.json';
import rawQatar from './qatar.json';
import rawRepublicOfTheCongo from './republic-of-the-congo.json';
import rawRomania from './romania.json';
import rawRussia from './russia.json';
import rawRwanda from './rwanda.json';
import rawSaintKittsAndNevis from './saint-kitts-and-nevis.json';
import rawSaintLucia from './saint-lucia.json';
import rawSaintVincentAndTheGrenadines from './saint-vincent-and-the-grenadines.json';
import rawSamoa from './samoa.json';
import rawSanMarino from './san-marino.json';
import rawSaoTomeAndPrincipe from './sao-tome-and-principe.json';
import rawSaudiArabia from './saudi-arabia.json';
import rawSenegal from './senegal.json';
import rawSerbia from './serbia.json';
import rawSeychelles from './seychelles.json';
import rawSierraLeone from './sierra-leone.json';
import rawSingapore from './singapore.json';
import rawSlovakia from './slovakia.json';
import rawSlovenia from './slovenia.json';
import rawSolomonIslands from './solomon-islands.json';
import rawSomalia from './somalia.json';
import rawSouthAfrica from './south-africa.json';
import rawSouthKorea from './south-korea.json';
import rawSouthSudan from './south-sudan.json';
import rawSpain from './spain.json';
import rawSriLanka from './sri-lanka.json';
import rawSudan from './sudan.json';
import rawSuriname from './suriname.json';
import rawSweden from './sweden.json';
import rawSwitzerland from './switzerland.json';
import rawSyria from './syria.json';
import rawTaiwan from './taiwan.json';
import rawTajikistan from './tajikistan.json';
import rawTanzania from './tanzania.json';
import rawThailand from './thailand.json';
import rawTheGambia from './the-gambia.json';
import rawTimorLeste from './timor-leste.json';
import rawTogo from './togo.json';
import rawTonga from './tonga.json';
import rawTrinidadAndTobago from './trinidad-and-tobago.json';
import rawTunisia from './tunisia.json';
import rawTurkey from './turkey.json';
import rawTurkmenistan from './turkmenistan.json';
import rawTuvalu from './tuvalu.json';
import rawUganda from './uganda.json';
import rawUkraine from './ukraine.json';
import rawUnitedArabEmirates from './united-arab-emirates.json';
import rawUnitedKingdom from './united-kingdom.json';
import rawUnitedStates from './united-states.json';
import rawUruguay from './uruguay.json';
import rawUzbekistan from './uzbekistan.json';
import rawVanuatu from './vanuatu.json';
import rawVaticanCity from './vatican-city.json';
import rawVenezuela from './venezuela.json';
import rawVietnam from './vietnam.json';
import rawYemen from './yemen.json';
import rawZambia from './zambia.json';
import rawZimbabwe from './zimbabwe.json';

export const RAW_COUNTRY_DOCUMENTS: readonly unknown[] = [
  rawAfghanistan,
  rawAlbania,
  rawAlgeria,
  rawAndorra,
  rawAngola,
  rawAntiguaAndBarbuda,
  rawArgentina,
  rawArmenia,
  rawAustralia,
  rawAustria,
  rawAzerbaijan,
  rawBahamas,
  rawBahrain,
  rawBangladesh,
  rawBarbados,
  rawBelarus,
  rawBelgium,
  rawBelize,
  rawBenin,
  rawBhutan,
  rawBolivia,
  rawBosniaAndHerzegovina,
  rawBotswana,
  rawBrazil,
  rawBrunei,
  rawBulgaria,
  rawBurkinaFaso,
  rawBurundi,
  rawCambodia,
  rawCameroon,
  rawCanada,
  rawCapeVerde,
  rawCentralAfricanRepublic,
  rawChad,
  rawChile,
  rawChina,
  rawColombia,
  rawComoros,
  rawCostaRica,
  rawCroatia,
  rawCuba,
  rawCyprus,
  rawCzechRepublic,
  rawDemocraticRepublicOfTheCongo,
  rawDenmark,
  rawDjibouti,
  rawDominica,
  rawDominicanRepublic,
  rawEcuador,
  rawEgypt,
  rawElSalvador,
  rawEquatorialGuinea,
  rawEritrea,
  rawEstonia,
  rawEswatini,
  rawEthiopia,
  rawFederatedStatesOfMicronesia,
  rawFiji,
  rawFinland,
  rawFrance,
  rawGabon,
  rawGeorgia,
  rawGermany,
  rawGhana,
  rawGibraltar,
  rawGreece,
  rawGreenland,
  rawGrenada,
  rawGuatemala,
  rawGuinea,
  rawGuineaBissau,
  rawGuyana,
  rawHaiti,
  rawHonduras,
  rawHungary,
  rawIceland,
  rawIndia,
  rawIndonesia,
  rawIran,
  rawIraq,
  rawIreland,
  rawIsrael,
  rawItaly,
  rawIvoryCoast,
  rawJamaica,
  rawJapan,
  rawJordan,
  rawKazakhstan,
  rawKenya,
  rawKingdomOfTheNetherlands,
  rawKiribati,
  rawKosovo,
  rawKuwait,
  rawKyrgyzstan,
  rawLaos,
  rawLatvia,
  rawLebanon,
  rawLesotho,
  rawLiberia,
  rawLibya,
  rawLiechtenstein,
  rawLithuania,
  rawLuxembourg,
  rawMadagascar,
  rawMalawi,
  rawMalaysia,
  rawMaldives,
  rawMali,
  rawMalta,
  rawMarshallIslands,
  rawMauritania,
  rawMauritius,
  rawMexico,
  rawMoldova,
  rawMonaco,
  rawMongolia,
  rawMontenegro,
  rawMorocco,
  rawMozambique,
  rawMyanmar,
  rawNamibia,
  rawNauru,
  rawNepal,
  rawNewZealand,
  rawNicaragua,
  rawNiger,
  rawNigeria,
  rawNorthKorea,
  rawNorthMacedonia,
  rawNorway,
  rawOman,
  rawPakistan,
  rawPalau,
  rawPalestine,
  rawPanama,
  rawPapuaNewGuinea,
  rawParaguay,
  rawPeru,
  rawPhilippines,
  rawPoland,
  rawPortugal,
  rawQatar,
  rawRepublicOfTheCongo,
  rawRomania,
  rawRussia,
  rawRwanda,
  rawSaintKittsAndNevis,
  rawSaintLucia,
  rawSaintVincentAndTheGrenadines,
  rawSamoa,
  rawSanMarino,
  rawSaoTomeAndPrincipe,
  rawSaudiArabia,
  rawSenegal,
  rawSerbia,
  rawSeychelles,
  rawSierraLeone,
  rawSingapore,
  rawSlovakia,
  rawSlovenia,
  rawSolomonIslands,
  rawSomalia,
  rawSouthAfrica,
  rawSouthKorea,
  rawSouthSudan,
  rawSpain,
  rawSriLanka,
  rawSudan,
  rawSuriname,
  rawSweden,
  rawSwitzerland,
  rawSyria,
  rawTaiwan,
  rawTajikistan,
  rawTanzania,
  rawThailand,
  rawTheGambia,
  rawTimorLeste,
  rawTogo,
  rawTonga,
  rawTrinidadAndTobago,
  rawTunisia,
  rawTurkey,
  rawTurkmenistan,
  rawTuvalu,
  rawUganda,
  rawUkraine,
  rawUnitedArabEmirates,
  rawUnitedKingdom,
  rawUnitedStates,
  rawUruguay,
  rawUzbekistan,
  rawVanuatu,
  rawVaticanCity,
  rawVenezuela,
  rawVietnam,
  rawYemen,
  rawZambia,
  rawZimbabwe,
];
