/**
 * GENERATED FILE — one import per document in this directory.
 * Regenerated by the data pipeline (@fathom/pipeline) on apply; keep in
 * sync by hand only when adding documents manually.
 */
import rawBabElMandeb from './bab-el-mandeb.json';
import rawBass from './bass.json';
import rawBelleisle from './belleisle.json';
import rawBering from './bering.json';
import rawBonifacio from './bonifacio.json';
import rawBosporus from './bosporus.json';
import rawCook from './cook.json';
import rawDardanelles from './dardanelles.json';
import rawDavis from './davis.json';
import rawDenmark from './denmark.json';
import rawDover from './dover.json';
import rawFlorida from './florida.json';
import rawGeorgia from './georgia.json';
import rawGibraltar from './gibraltar.json';
import rawHormuz from './hormuz.json';
import rawHudson from './hudson.json';
import rawJuandefuca from './juandefuca.json';
import rawKarimata from './karimata.json';
import rawKattegat from './kattegat.json';
import rawKerch from './kerch.json';
import rawKorea from './korea.json';
import rawLaperouse from './laperouse.json';
import rawLombok from './lombok.json';
import rawLuzon from './luzon.json';
import rawMagellan from './magellan.json';
import rawMakassar from './makassar.json';
import rawMalacca from './malacca.json';
import rawMessina from './messina.json';
import rawMozambique from './mozambique.json';
import rawNares from './nares.json';
import rawNorthumberland from './northumberland.json';
import rawOresund from './oresund.json';
import rawOtranto from './otranto.json';
import rawPalk from './palk.json';
import rawSingapore from './singapore.json';
import rawSkagerrak from './skagerrak.json';
import rawSolent from './solent.json';
import rawSunda from './sunda.json';
import rawTaiwan from './taiwan.json';
import rawTorres from './torres.json';
import rawTsugaru from './tsugaru.json';
import rawVilkitsky from './vilkitsky.json';

export const RAW_STRAIT_DOCUMENTS: readonly unknown[] = [
  rawBabElMandeb,
  rawBass,
  rawBelleisle,
  rawBering,
  rawBonifacio,
  rawBosporus,
  rawCook,
  rawDardanelles,
  rawDavis,
  rawDenmark,
  rawDover,
  rawFlorida,
  rawGeorgia,
  rawGibraltar,
  rawHormuz,
  rawHudson,
  rawJuandefuca,
  rawKarimata,
  rawKattegat,
  rawKerch,
  rawKorea,
  rawLaperouse,
  rawLombok,
  rawLuzon,
  rawMagellan,
  rawMakassar,
  rawMalacca,
  rawMessina,
  rawMozambique,
  rawNares,
  rawNorthumberland,
  rawOresund,
  rawOtranto,
  rawPalk,
  rawSingapore,
  rawSkagerrak,
  rawSolent,
  rawSunda,
  rawTaiwan,
  rawTorres,
  rawTsugaru,
  rawVilkitsky,
];
