import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import type { Source } from '@fathom/data';

import type { StagedEntity } from './types';

/** Where each per-file collection lives in the data package. */
const PER_FILE_COLLECTIONS: Record<string, { dir: string; constName: string }> = {
  strait: { dir: 'straits', constName: 'RAW_STRAIT_DOCUMENTS' },
  'water-body': { dir: 'water-bodies', constName: 'RAW_WATER_BODY_DOCUMENTS' },
  country: { dir: 'countries', constName: 'RAW_COUNTRY_DOCUMENTS' },
};

/** Array-file collections in the data package. */
const ARRAY_COLLECTIONS: Record<string, string> = {
  port: 'maritime/ports.json',
  canal: 'maritime/canals.json',
  bridge: 'maritime/bridges.json',
  tunnel: 'maritime/tunnels.json',
  island: 'maritime/islands.json',
  'maritime-route': 'maritime/routes.json',
};

const camel = (id: string) =>
  'raw' +
  id
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

/** Regenerates a collection's manifest module from its directory listing. */
export function renderManifest(ids: readonly string[], constName: string): string {
  const sorted = [...ids].sort();
  return `/**
 * GENERATED FILE — one import per document in this directory.
 * Regenerated by the data pipeline (@fathom/pipeline) on apply; keep in
 * sync by hand only when adding documents manually.
 */
${sorted.map((id) => `import ${camel(id)} from './${id}.json';`).join('\n')}

export const ${constName}: readonly unknown[] = [
${sorted.map((id) => `  ${camel(id)},`).join('\n')}
];
`;
}

/**
 * Applies a staged import to the data package: writes documents, appends
 * index entries, merges new sources, and regenerates manifests. Meant to
 * run after the report has been reviewed.
 */
export async function applyStaged(
  dataSrcDir: string,
  staged: readonly StagedEntity[],
  stagedSources: readonly Source[],
): Promise<readonly string[]> {
  const applied: string[] = [];

  for (const entity of staged) {
    const perFile = PER_FILE_COLLECTIONS[entity.type];
    if (perFile) {
      const dir = join(dataSrcDir, perFile.dir);
      await writeFile(
        join(dir, `${entity.id}.json`),
        JSON.stringify(entity.document, null, 2) + '\n',
      );

      const indexPath = join(dir, 'index.json');
      const index = JSON.parse(await readFile(indexPath, 'utf8')) as Record<string, unknown>[];
      if (!index.some((entry) => entry.id === entity.id)) {
        index.push(indexEntryFor(entity));
        await writeFile(indexPath, JSON.stringify(index, null, 2) + '\n');
      }

      const ids = (await readdir(dir))
        .filter((file) => file.endsWith('.json') && file !== 'index.json')
        .map((file) => file.slice(0, -5));
      await writeFile(join(dir, 'manifest.ts'), renderManifest(ids, perFile.constName));
      applied.push(`${entity.type}:${entity.id}`);
      continue;
    }

    const arrayFile = ARRAY_COLLECTIONS[entity.type];
    if (arrayFile) {
      const path = join(dataSrcDir, arrayFile);
      const collection = JSON.parse(await readFile(path, 'utf8')) as Record<string, unknown>[];
      if (!collection.some((doc) => doc.id === entity.id)) {
        collection.push(entity.document);
        await writeFile(path, JSON.stringify(collection, null, 2) + '\n');
      }
      applied.push(`${entity.type}:${entity.id}`);
    }
  }

  if (stagedSources.length > 0) {
    const path = join(dataSrcDir, 'knowledge/sources.json');
    const sources = JSON.parse(await readFile(path, 'utf8')) as Record<string, unknown>[];
    for (const source of stagedSources) {
      if (!sources.some((existing) => existing.id === source.id)) {
        sources.push(source);
      }
    }
    await writeFile(path, JSON.stringify(sources, null, 2) + '\n');
  }

  return applied;
}

function indexEntryFor(entity: StagedEntity): Record<string, unknown> {
  const doc = entity.document;
  switch (entity.type) {
    case 'strait':
      return {
        id: doc.id,
        name: doc.name,
        region: doc.region,
        countries: doc.countries,
        lat: doc.lat,
        lon: doc.lon,
      };
    case 'water-body':
      return { id: doc.id, name: doc.name, type: doc.type };
    case 'country':
      return { id: doc.id, name: doc.name, ...(doc.code ? { code: doc.code } : {}) };
    default:
      return { id: doc.id, name: doc.name };
  }
}

export async function writeStagedBundle(
  outDir: string,
  staged: readonly StagedEntity[],
  stagedSources: readonly Source[],
  report: unknown,
  searchDocuments: readonly unknown[],
): Promise<void> {
  await mkdir(join(outDir, 'entities'), { recursive: true });
  for (const entity of staged) {
    await mkdir(join(outDir, 'entities', entity.type), { recursive: true });
    await writeFile(
      join(outDir, 'entities', entity.type, `${entity.id}.json`),
      JSON.stringify(entity.document, null, 2) + '\n',
    );
  }
  await writeFile(join(outDir, 'staged.json'), JSON.stringify({ staged, stagedSources }, null, 2));
  await writeFile(join(outDir, 'report.json'), JSON.stringify(report, null, 2));
  await writeFile(join(outDir, 'search-documents.json'), JSON.stringify(searchDocuments, null, 2));
}
