/**
 * GENERATED FILE — one import per document in this directory.
 * Regenerated by the data pipeline (@fathom/pipeline) on apply; keep in
 * sync by hand only when adding documents manually.
 */
import rawAdriaticSea from './adriatic-sea.json';
import rawAegeanSea from './aegean-sea.json';
import rawAndamanSea from './andaman-sea.json';
import rawArafuraSea from './arafura-sea.json';
import rawArcticOcean from './arctic-ocean.json';
import rawAtlanticOcean from './atlantic-ocean.json';
import rawBaffinBay from './baffin-bay.json';
import rawBalticApproaches from './baltic-approaches.json';
import rawBalticSea from './baltic-sea.json';
import rawBayOfBengal from './bay-of-bengal.json';
import rawBlackSea from './black-sea.json';
import rawCelebesSea from './celebes-sea.json';
import rawCoralSea from './coral-sea.json';
import rawEastChinaSea from './east-china-sea.json';
import rawEnglishChannel from './english-channel.json';
import rawGreenlandSea from './greenland-sea.json';
import rawGulfOfAden from './gulf-of-aden.json';
import rawGulfOfMexico from './gulf-of-mexico.json';
import rawGulfOfOman from './gulf-of-oman.json';
import rawGulfOfStLawrence from './gulf-of-st-lawrence.json';
import rawHudsonBay from './hudson-bay.json';
import rawIndianOcean from './indian-ocean.json';
import rawIonianSea from './ionian-sea.json';
import rawJavaSea from './java-sea.json';
import rawKaraSea from './kara-sea.json';
import rawKattegat from './kattegat.json';
import rawLabradorSea from './labrador-sea.json';
import rawLaptevSea from './laptev-sea.json';
import rawMalaccaStrait from './malacca-strait.json';
import rawMediterraneanSea from './mediterranean-sea.json';
import rawNorthSea from './north-sea.json';
import rawPacificOcean from './pacific-ocean.json';
import rawPalkBay from './palk-bay.json';
import rawPersianGulf from './persian-gulf.json';
import rawPhilippineSea from './philippine-sea.json';
import rawRedSea from './red-sea.json';
import rawSalishSea from './salish-sea.json';
import rawSeaOfAzov from './sea-of-azov.json';
import rawSeaOfJapan from './sea-of-japan.json';
import rawSeaOfMarmara from './sea-of-marmara.json';
import rawSeaOfOkhotsk from './sea-of-okhotsk.json';
import rawSkagerrak from './skagerrak.json';
import rawSouthChinaSea from './south-china-sea.json';
import rawSouthernOcean from './southern-ocean.json';
import rawTasmanSea from './tasman-sea.json';
import rawTyrrhenianSea from './tyrrhenian-sea.json';

export const RAW_WATER_BODY_DOCUMENTS: readonly unknown[] = [
  rawAdriaticSea,
  rawAegeanSea,
  rawAndamanSea,
  rawArafuraSea,
  rawArcticOcean,
  rawAtlanticOcean,
  rawBaffinBay,
  rawBalticApproaches,
  rawBalticSea,
  rawBayOfBengal,
  rawBlackSea,
  rawCelebesSea,
  rawCoralSea,
  rawEastChinaSea,
  rawEnglishChannel,
  rawGreenlandSea,
  rawGulfOfAden,
  rawGulfOfMexico,
  rawGulfOfOman,
  rawGulfOfStLawrence,
  rawHudsonBay,
  rawIndianOcean,
  rawIonianSea,
  rawJavaSea,
  rawKaraSea,
  rawKattegat,
  rawLabradorSea,
  rawLaptevSea,
  rawMalaccaStrait,
  rawMediterraneanSea,
  rawNorthSea,
  rawPacificOcean,
  rawPalkBay,
  rawPersianGulf,
  rawPhilippineSea,
  rawRedSea,
  rawSalishSea,
  rawSeaOfAzov,
  rawSeaOfJapan,
  rawSeaOfMarmara,
  rawSeaOfOkhotsk,
  rawSkagerrak,
  rawSouthChinaSea,
  rawSouthernOcean,
  rawTasmanSea,
  rawTyrrhenianSea,
];
